# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Java Package

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: |
          chmod 777 mvnw
          ./mvnw package -Dmaven.test.skip=true
      - name: Push
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./target/*.jar
          target: /home/workplace/authority_java/
#
#  install-and-run:
#    needs: build-and-push
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install and run
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          command_timeout: 20m
#          script: |
#            cd /home/workplace/leetcode_rank_frontend/
#            sh opt.sh stop leetcode_rank_frontend
#            sh opt.sh kill_by_port 3001
#            sh opt.sh delete_container leetcode_rank_frontend
#            sh opt.sh delete_image leetcode_rank_frontend
#            docker-compose up -d
#            cd ..
#            rm -rf /home/workplace/leetcode_rank_frontend/
